/// Flutter icons ShibankIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ShibankIcons
///      fonts:
///       - asset: fonts/ShibankIcons.ttf
///
/// 
/// * Iconic, Copyright (C) 2012 by P.J. Onori
///         Author:    P.J. Onori
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://somerandomdude.com/work/iconic/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class ShibankIcons {
  ShibankIcons._();

  static const _kFontFam = 'ShibankIcons';
  static const _kFontPkg = null;

  static const IconData exchange = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData list_alt = IconData(0xf022, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chart_pie = IconData(0xf200, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_secret = IconData(0xf21b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fingerprint = IconData(0xf577, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData globe_americas = IconData(0xf57d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hotel = IconData(0xf594, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
